CREATE TABLE AUDIT_LOG_ENTRIES (
  ENTRY_ID NUMBER UNIQUE NOT NULL,
  LOG_LEVEL INTEGER,
  MESSAGE VARCHAR(4096),
  USERID VARCHAR(255),
  IPADDR VARCHAR(255),
  ADDED TIMESTAMP WITH LOCAL TIME ZONE DEFAULT sysdate,
  HAPPENED TIMESTAMP WITH LOCAL TIME ZONE
)
